/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskUpdateSchema } from '../../models/task-update-schema';

export interface UpdateTaskEndpointTasksTaskIdPatch$Params {
  task_id: number;
      body: TaskUpdateSchema
}

export function updateTaskEndpointTasksTaskIdPatch(http: HttpClient, rootUrl: string, params: UpdateTaskEndpointTasksTaskIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateTaskEndpointTasksTaskIdPatch.PATH, 'patch');
  if (params) {
    rb.path('task_id', params.task_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateTaskEndpointTasksTaskIdPatch.PATH = '/tasks/{task_id}';
