/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserUpdateSchema } from '../../models/user-update-schema';

export interface UpdateUserUsersUserIdPatch$Params {
  user_id: number;
  body: UserUpdateSchema;
}

export function updateUserUsersUserIdPatch(
  http: HttpClient,
  rootUrl: string,
  params: UpdateUserUsersUserIdPatch$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateUserUsersUserIdPatch.PATH, 'patch');
  if (params) {
    rb.path('user_id', params.user_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    }),
  );
}

updateUserUsersUserIdPatch.PATH = '/users/{user_id}';
