/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetCommentsByTaskCommentsByTaskTaskIdGet$Params {
  task_id: number;
}

export function getCommentsByTaskCommentsByTaskTaskIdGet(http: HttpClient, rootUrl: string, params: GetCommentsByTaskCommentsByTaskTaskIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, getCommentsByTaskCommentsByTaskTaskIdGet.PATH, 'get');
  if (params) {
    rb.path('task_id', params.task_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

getCommentsByTaskCommentsByTaskTaskIdGet.PATH = '/comments/by_task/{task_id}';
