/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';

export interface GetCommentPhotosByObjectCommentsByObjectObjectIdGet$Params {
  object_id: number;
}

export function getCommentPhotosByObjectCommentsByObjectObjectIdGet(
  http: HttpClient,
  rootUrl: string,
  params: GetCommentPhotosByObjectCommentsByObjectObjectIdGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(
    rootUrl,
    getCommentPhotosByObjectCommentsByObjectObjectIdGet.PATH,
    'get',
  );
  if (params) {
    rb.path('object_id', params.object_id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    }),
  );
}

getCommentPhotosByObjectCommentsByObjectObjectIdGet.PATH = '/comments/by_object/{object_id}';
