/* tslint:disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BodyCreateCommentAsTaskCommentsPost } from './models/body-create-comment-as-task-comments-post';
export type { BotCreate } from './models/bot-create';
export type { CreateBuyerModel } from './models/create-buyer-model';
export type { HttpValidationError } from './models/http-validation-error';
export type { RoleSchema } from './models/role-schema';
export type { TaskCreate } from './models/task-create';
export type { TaskStageCreate } from './models/task-stage-create';
export type { TaskStageUpdate } from './models/task-stage-update';
export type { TaskTypeCreate } from './models/task-type-create';
export type { TaskTypeUpdate } from './models/task-type-update';
export type { TaskUpdateSchema } from './models/task-update-schema';
export type { TelegramAuthor } from './models/telegram-author';
export type { UserAuthorize } from './models/user-authorize';
export type { UserCreate } from './models/user-create';
export type { UserUpdateSchema } from './models/user-update-schema';
export type { ValidationError } from './models/validation-error';
