/* tslint:disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthentificateService } from './services/authentificate.service';
export { MarketingService } from './services/marketing.service';
export { PriceService } from './services/price.service';
export { Service } from './services/service';
export { TaskStagesService } from './services/task-stages.service';
export { TaskTypesService } from './services/task-types.service';
export { TasksService } from './services/tasks.service';
export { UsersService } from './services/users.service';
