/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface GetBuyerItemsPriceTypeIdGet$Params {
  type_id: any;
}

export function getBuyerItemsPriceTypeIdGet(
  http: HttpClient,
  rootUrl: string,
  params: GetBuyerItemsPriceTypeIdGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, getBuyerItemsPriceTypeIdGet.PATH, 'get');
  if (params) {
    rb.path('type_id', params.type_id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    }),
  );
}

getBuyerItemsPriceTypeIdGet.PATH = '/price/{type_id}';
