/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetTaskTypesAndStagesTasksTypesGet$Params {
  task_type_id_or_name?: (number | string | null);
  parent_id?: (number | null);
}

export function getTaskTypesAndStagesTasksTypesGet(http: HttpClient, rootUrl: string, params?: GetTaskTypesAndStagesTasksTypesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, getTaskTypesAndStagesTasksTypesGet.PATH, 'get');
  if (params) {
    rb.query('task_type_id_or_name', params.task_type_id_or_name, {});
    rb.query('parent_id', params.parent_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

getTaskTypesAndStagesTasksTypesGet.PATH = '/tasks/types/';
