/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BodyCreateCommentAsTaskCommentsPost {
  audios?: Array<Blob> | null;
  files?: Array<Blob> | null;
  photos?: Array<Blob> | null;
  task_id: number;
  value?: string | null;
  videos?: Array<Blob> | null;
}
