/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskTypeCreate {
  parent_id?: number | null;
  responsible_role_id?: number | null;

  /**
   * Название типа задачи
   */
  value: string;
}
