/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskStageUpdate {
  id: number;
  parent_id?: number | null;
  task_type_id?: number | null;
  value?: string | null;
}
