/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskCreate {
  meta_data?: ({
} | null);
  parent_id?: (number | null);
  type_id?: (number | null);
  value: string;
}
