/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskTypeUpdate {
  id: number;
  parent_id?: (number | null);
  responsible_role_id?: (number | null);
  value?: (string | null);
}
