/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskUpdateSchema {
  meta_data?: {} | null;
  parent_id?: number | null;
  stage_id?: number | null;
  value?: string | null;
}
