/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskStageCreate {
  parent_id?: (number | null);
  task_type_id: number;
  value: string;
}
