/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserCreate {
  first_name: string;
  last_name: string;
  login: string;
  password: string;
  patronymic: string;
  phone: string;
  roles: Array<any>;
}
