/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

import { BotCreate } from '../../models/bot-create';

export interface RegisterBotAuthTelegramSignUpPost$Params {
  body: BotCreate;
}

export function registerBotAuthTelegramSignUpPost(
  http: HttpClient,
  rootUrl: string,
  params: RegisterBotAuthTelegramSignUpPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, registerBotAuthTelegramSignUpPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    }),
  );
}

registerBotAuthTelegramSignUpPost.PATH = '/auth/telegram/sign-up';
